backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

site_url: https://cocopoca.github.io
display_url: https://cocopoca.github.io

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "source/_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
