backend:
  name: github
  repo: cocopoca/cocopoca.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  client_id: Ov23liYOS0XJumrRLDjA

site_url: https://cocopoca.github.io
display_url: https://cocopoca.github.io

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "source/_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
